### ISSUE TITLE
Cannot get download to work with Vaadin 14.6.7 and demo does not work

### ISSUE THREAD

**Issue by bliblablop** [stefanuebe/vaadin-lazy-download-button#7]
Hi Stefan,

Is this component still being maintained? I cannot get either the demo at https://stefan.app.fi/lazy-download-button-demo/ to work (only the eager button works) and the integration in my application also does not work. Sometimes there is after some minutes a browser download popup saying there was an error downloading but thats it.

Thx for checking.

**Comment by stefanuebe** [comment]
Hi, yes, the addon is maintained, I'll try to check it these days.

**Comment by stefanuebe** [comment]
Have you tried to get it run in your app? Might be, that simply the demo is broken.

**Comment by stefanuebe** [comment]
*deleted previous comment
Sorry, I simply misread your issue description regarding if you tried it out in your app. Also sorry for the long response time, busy times.

It seems like I just had an issue with my demo fetching the file from the correct place, not sure why that did not work anymore. I fixed the issue, updated the demo to the latest V14 and also migrated it to a Spring Boot project (but this one only has affects the download file location).

Therefore it seems to be an issue with the demo / sample "only". Can you please check, if the file is fetched and provided as a stream correctly in your app?
